---

- name: Apache server installation
  hosts: webservers
  user: ec2-user
  become: yes

  tasks:
   - name: install httpd
     yum:
       name: httpd
       state: present

   - name: start service httpd
     service:
       name: httpd
       state: started
       enabled: yes

   - name: create index.html file here
     copy:
       dest: /var/www/html/index.html
       content: "<h1> Hare Krishna Hare Krishna Krishna Krishna Hare Hare, Hare Rama Hare Rama Rama Rama Hare Hare </h1>"

       
