- name: install the packages
  yum: 
    name: "{{install_packages}}"
    state: present
  



- name: run the httpd service
  service: 
    name: "{{item}}"
    enabled: yes
    state: started

  loop: 
    
   - docker
   - httpd


- name: create index file 
  copy:
     dest: /var/www/html/index.html
     content: "<h1> hare krishna </h1>"


